name: bblean
channels:
  - nodefaults
  - https://conda.anaconda.org/conda-forge
dependencies:
  # General
  - python=3.11
  - pip>=24.0  # Installs python packages
  # Build system
  - setuptools>=64
  - setuptools-scm>=8
  # Automatic linters / checkers / tests / CI
  - pre-commit  # Runs pre commit/push hooks
  - black  # Code formatter
  - flake8  # PEP8 linter
  - autoflake  # Remove unused imports / variables
  - mypy  # Type checker
  # Non automatic CI
  - pytest  # Python testing framework
  - cruft # Keep up with cookiecutter updates
  # Profiling tools
  - memray
  - py-spy

  # Docs
  - sphinx  # Documentation framework, uses restructured text (.rst)

  # CLI
  - typer  # Handy cli library with support for type checking
  - rich  # Colorful styles and terminal outputs
  # Other
  - scipy 
  - rdkit
  - numpy
  - psutil
#  Required for example notebooks
  - pandas
  - tqdm
  - seaborn
  - statsmodels
  - scikit-learn
  - matplotlib
  - jupytext  # Simple text conversion of notebooks
# useful_rdkit_utils
