name: bblean
channels:
  - nodefaults
  - https://conda.anaconda.org/conda-forge
dependencies:
  # General
  - python=3.11
  - pip>=25.0  # Installs python packages

  # Build system
  - setuptools>=75.6
  - setuptools-scm>=9

  # Core dependencies
  - scipy 
  - rdkit
  - numpy>=2.0
  - pandas
  - psutil
  - matplotlib
  - scikit-learn
  # CLI
  - typer  # Handy cli library with support for type checking
  - rich  # Colorful styles and terminal outputs

  # Dev dependencies: linters / checkers / tests / CI / profilers
  - pre-commit  # Runs pre commit/push hooks
  - black  # Code formatter
  - flake8  # PEP8 linter
  - autoflake  # Remove unused imports / variables
  - mypy  # Type checker
  - pytest  # Python testing framework
  - pytest-subtests
  - cruft # Keep up with cookiecutter updates
  - coverage
  # Profilers
  - memray
  - py-spy
  # Docs
  - sphinx  # Documentation framework, uses restructured text (.rst)
  # Loading and converting jupyter notebooks
  - jupyter
  - jupytext

#  Required for example dataset_splitting notebook only
# - tqdm
# - seaborn
# - statsmodels
# - useful_rdkit_utils
